name: Build Kernel Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile inside precise container
      uses: docker://ubuntu:14.04
      with:
        args: >
          bash -c "
          apt-get update &&
          apt-get install -y gcc-arm-linux-gnueabi build-essential ncurses-dev bc bison flex libssl-dev &&
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- rk30_hdbox_defconfig &&
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- -j$(nproc) &&
          ./mkkrnlimg arch/arm/boot/zImage recovery.img
          "

    - name: Upload Finished Image
      uses: actions/upload-artifact@v4
      with:
        name: finished-recovery-image
        path: recovery.img
